### ISSUE TITLE
Missing rel_eps parameter in lib

### ISSUE THREAD

**Issue by schmittjoaopedro** [ibex-team/ibex-java#4]
Hello,

Some time ago there was a discussin about a rel_eps parameter to control the contraction ratio. I think this parameter wasn't migrate to this repository.
Is possible to add the same parameter here with a override to the contract method? I think it's a good idea to keep the backward compatibility with previous versions.

Links for reference:
* https://github.com/ibex-team/ibex-lib/commit/a15497d7e70a35f59d61feb4e507a59a317eea06
* https://github.com/ibex-team/ibex-lib/issues/435
* https://github.com/chocoteam/choco-solver/issues/653

**Comment by gchabert** [comment]
You are right, I must have mixed up something when I created the repository for ibex-java :(
I'm fixing it.

**Comment by gchabert** [comment]
It's done. The reason was that I inconsiderately transferred the master branch at a point where it was not fully merged with develop.
I've made a new release : https://github.com/ibex-team/ibex-java/releases/tag/1.1.0
Sorry for the inconvenience.
